# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spacectl < Formula
  desc "Spacelift client and CLI"
  homepage "https://github.com/spacelift-io/spacectl"
  version "1.15.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spacelift-io/spacectl/releases/download/v1.15.1/spacectl_1.15.1_darwin_amd64.zip"
      sha256 "94876520c4fed1cb89b4a18d68ab41f5bb6b1d26d706ea4921089e5457949ee4"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spacelift-io/spacectl/releases/download/v1.15.1/spacectl_1.15.1_darwin_arm64.zip"
      sha256 "f728aa6a869027c7a50c9673fe6b46bd8bc3389edbc953eb37e9ac070c9ac699"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spacelift-io/spacectl/releases/download/v1.15.1/spacectl_1.15.1_linux_amd64.zip"
      sha256 "365897f1f46189c642eb5b1dfb4801fa2722882c04d91e174422cc2db89b97ba"
      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spacelift-io/spacectl/releases/download/v1.15.1/spacectl_1.15.1_linux_arm64.zip"
      sha256 "63f16ce0e5ed514ea80e106dc64d2a730366c40af5af8fecc4ccc6b707b060bd"
      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
  end
end
