# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spacectl < Formula
  desc "Spacelift client and CLI"
  homepage "https://github.com/spacelift-io/spacectl"
  version "1.7.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/spacelift-io/spacectl/releases/download/v1.7.0/spacectl_1.7.0_darwin_amd64.zip"
      sha256 "6561acd41e4e3929c00ffe9e3f3d7f71cc680abd3c61ceee1dea8c0d342cac30"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
    on_arm do
      url "https://github.com/spacelift-io/spacectl/releases/download/v1.7.0/spacectl_1.7.0_darwin_arm64.zip"
      sha256 "e468fe886e291bc7f5e139d5b0081a2c51e5710746c556bf36115906d8b5ece9"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/spacelift-io/spacectl/releases/download/v1.7.0/spacectl_1.7.0_linux_amd64.zip"
        sha256 "09232586d67ed90dc1eaa7289e361277cb0be9992d85fe0a7e369892384d73c0"

        def install
          bin.install "spacectl"
          bash_completion.install "completions/spacectl.bash" => "spacectl"
          zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
          fish_completion.install "completions/spacectl.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/spacelift-io/spacectl/releases/download/v1.7.0/spacectl_1.7.0_linux_arm64.zip"
        sha256 "6f3c8a93f02189a8e2e8b9b6b91a48a411abce99244167dba49cd93c93b85ed6"

        def install
          bin.install "spacectl"
          bash_completion.install "completions/spacectl.bash" => "spacectl"
          zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
          fish_completion.install "completions/spacectl.fish"
        end
      end
    end
  end
end
