# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpaceliftIntent < Formula
  desc "Spacelift Intent MCP Server"
  homepage "https://github.com/spacelift-io/spacelift-intent"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spacelift-io/spacelift-intent/releases/download/v0.1.1/spacelift-intent_0.1.1_darwin_amd64.zip"
      sha256 "85ddf44786709c44880b49e86a770c182cbeb6688f21ef45a1a8257bdc9b3683"

      def install
        bin.install "spacelift-intent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spacelift-io/spacelift-intent/releases/download/v0.1.1/spacelift-intent_0.1.1_darwin_arm64.zip"
      sha256 "eeaac556850e8595b7743ad861f7cc0e5f74607f2feb649c6fe89381928049ab"

      def install
        bin.install "spacelift-intent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spacelift-io/spacelift-intent/releases/download/v0.1.1/spacelift-intent_0.1.1_linux_amd64.zip"
      sha256 "8877d755489072d349c086cf8a8e1271a1b68f6647d7bf77dbdd14cb1b3fda10"
      def install
        bin.install "spacelift-intent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spacelift-io/spacelift-intent/releases/download/v0.1.1/spacelift-intent_0.1.1_linux_arm64.zip"
      sha256 "11ea35ea4fa2dc4e27726e1e6b0ab37351b8ded080d9762051ed0d92b62105de"
      def install
        bin.install "spacelift-intent"
      end
    end
  end
end
