# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpaceliftIntent < Formula
  desc "Spacelift Intent MCP Server"
  homepage "https://github.com/spacelift-io/spacelift-intent"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spacelift-io/spacelift-intent/releases/download/v0.1.0/spacelift-intent_0.1.0_darwin_amd64.zip"
      sha256 "d6d76be0c20c61a3bdf428515f023991a7f443d96fcecbb738447d7f10547aa0"

      def install
        bin.install "spacelift-intent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spacelift-io/spacelift-intent/releases/download/v0.1.0/spacelift-intent_0.1.0_darwin_arm64.zip"
      sha256 "36459ee7d5653575846e49b71d2e8b9f307e08e4b3a3bce94c300bf1da14d70a"

      def install
        bin.install "spacelift-intent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spacelift-io/spacelift-intent/releases/download/v0.1.0/spacelift-intent_0.1.0_linux_amd64.zip"
      sha256 "d735428e012b36671ada33bce9f79222c45aeed0d5c41d7bf51c7e815f5aaac1"
      def install
        bin.install "spacelift-intent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spacelift-io/spacelift-intent/releases/download/v0.1.0/spacelift-intent_0.1.0_linux_arm64.zip"
      sha256 "5a4f251ac7fa3387e221f700683e97c9f17cd89fa5e55bb646835529e29bcfa5"
      def install
        bin.install "spacelift-intent"
      end
    end
  end
end
