# This file was generated by GoReleaser. DO NOT EDIT.
cask "spacectl" do
  name "spacectl"
  desc "Spacelift client and CLI"
  homepage "https://github.com/spacelift-io/spacectl"
  version "1.21.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spacectl"
  bash_completion "completions/spacectl.bash"
  zsh_completion "completions/spacectl.zsh"
  fish_completion "completions/spacectl.fish"

  on_macos do
    on_intel do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_darwin_amd64.zip"
      sha256 "03bbd73b6edda70100fc8b02959882c5bfb6b51b2975fbf2a7f5d21613becebd"
    end
    on_arm do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_darwin_arm64.zip"
      sha256 "1c0a1afc329e35c69161911c22d4d06ffbb668bdb24b55c12789ceaee71d52b4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_linux_amd64.zip"
      sha256 "50d3ff096d64f10e9f55e46943f268840fab00d5480ab65719d9755e713bce45"
    end
    on_arm do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_linux_arm64.zip"
      sha256 "ff74af52a03683cd46a7e4269ff66970329c251830a53e03a335529ad5bdcb52"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spacectl"]
    end
  end

  # No zap stanza required
end
