# This file was generated by GoReleaser. DO NOT EDIT.
cask "spacectl" do
  name "spacectl"
  desc "Spacelift client and CLI"
  homepage "https://github.com/spacelift-io/spacectl"
  version "1.18.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spacectl"
  bash_completion "completions/spacectl.bash"
  zsh_completion "completions/spacectl.zsh"
  fish_completion "completions/spacectl.fish"

  on_macos do
    on_intel do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_darwin_amd64.zip"
      sha256 "09fe45628bcd7b8e8b768bc23c20ca23241fa9207b57ac8e24e509b21dde439c"
    end
    on_arm do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_darwin_arm64.zip"
      sha256 "fda94d6f6776458cab6ed9ce8cd5591f0ec6760e2f58124dc00274ec649791d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_linux_amd64.zip"
      sha256 "0a8a2b15ffb7ff7ac72f4c707b6074404bc7a038c1dcbd4ddbd463ec6528f711"
    end
    on_arm do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_linux_arm64.zip"
      sha256 "0c5fa9d7e36b310c8352671349b3abed34423d409b257b47b870eecef4dae053"
    end
  end

  # No zap stanza required
end
