# This file was generated by GoReleaser. DO NOT EDIT.
cask "spacectl" do
  name "spacectl"
  desc "Spacelift client and CLI"
  homepage "https://github.com/spacelift-io/spacectl"
  version "1.19.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spacectl"
  bash_completion "completions/spacectl.bash"
  zsh_completion "completions/spacectl.zsh"
  fish_completion "completions/spacectl.fish"

  on_macos do
    on_intel do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_darwin_amd64.zip"
      sha256 "5fdb1b85c169955eb0b97641b2c73a9c0c90b541720f4998467badccdb6236bd"
    end
    on_arm do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_darwin_arm64.zip"
      sha256 "fddf1b2253ca64baf3e3731ff9c92a5c40faf7576cc99df2de56edb32691df90"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_linux_amd64.zip"
      sha256 "0084753152122ed23107683b85befcb14b89aa3c4e587665217b0c205b614496"
    end
    on_arm do
      url "https://github.com/spacelift-io/spacectl/releases/download/v#{version}/spacectl_#{version}_linux_arm64.zip"
      sha256 "3a1342b576ef5fa7a2c88acaf46396c8b8faeec009af4b42fd9b526c9a9edfaf"
    end
  end

  # No zap stanza required
end
